---
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index CentOS
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repository index Ubuntu
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: install docker on Ubuntu
    apt:
      name: docker.io
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install docker on CentOS
    shell: 'curl -fsSL https://get.docker.com/ | sh'
    when: ansible_distribution == "CentOS"

  - name: install docker sdk on Ubuntu
    apt:
      name: python3-docker
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu"

  - name: docker permission on Ubuntu
    shell: 'sudo usermod -aG docker $USER'
    when: ansible_distribution == "Ubuntu"

  - name: install docker sdk on CentOS
    yum:
      name: python-docker-py
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: docker permission CentOS
    shell: 'sudo usermod -aG docker $(whoami)'
    when: ansible_distribution == "CentOS"

  - name: Enable and Start Docker
    service:
      name: docker
      state: started
 
  - name: copy dockerfile
    copy: src=Dockerfile dest=/briantjerome/container/

  - name: docker build
    docker_image:
      name: containerization
      build:
        path: /briantjerome/container/
        args:
          listen_port: 8080
      source: build
